---
# defaults file for openshift_prometheus
openshift_prometheus_state: present

openshift_prometheus_namespace: prometheus

openshift_prometheus_replicas: 1
openshift_prometheus_node_selector: {"region":"infra"}

# images
openshift_prometheus_image_proxy: "openshift/oauth-proxy:v1.0.0"
openshift_prometheus_image_prometheus: "openshift/prometheus:v2.0.0-dev"
openshift_prometheus_image_alertmanager: "openshift/prometheus-alertmanager:dev"
openshift_prometheus_image_alert_buffer: "ilackarms/message-buffer"

# additional prometheus rules file
openshift_prometheus_additional_rules_file: null

# storage
openshift_prometheus_storage_type: pvc
openshift_prometheus_pvc_name: prometheus
openshift_prometheus_pvc_size: 10G
openshift_prometheus_pvc_access_modes: [ReadWriteOnce]

openshift_prometheus_alertmanager_storage_type: pvc
openshift_prometheus_alertmanager_pvc_name: alertmanager
openshift_prometheus_alertmanager_pvc_size: 10G
openshift_prometheus_alertmanager_pvc_access_modes: [ReadWriteOnce]

openshift_prometheus_alert_buffer_storage_type: pvc
openshift_prometheus_alert_buffer_pvc_name: alert-buffer
openshift_prometheus_alert_buffer_pvc_size: 10G
openshift_prometheus_alert_buffer_pvc_access_modes: [ReadWriteOnce]

# container resources
openshift_prometheus_cpu_limit: null
openshift_prometheus_memory_limit: null
openshift_prometheus_cpu_requests: null
openshift_prometheus_memory_requests: null
openshift_prometheus_alertmanager_cpu_limit: null
openshift_prometheus_alertmanager_memory_limit: null
openshift_prometheus_alertmanager_cpu_requests: null
openshift_prometheus_alertmanager_memory_requests: null
openshift_prometheus_alert_buffer_cpu_limit: null
openshift_prometheus_alert_buffer_memory_limit: null
openshift_prometheus_alert_buffer_cpu_requests: null
openshift_prometheus_alert_buffer_memory_requests: null
openshift_prometheus_oauth_proxy_cpu_limit: null
openshift_prometheus_oauth_proxy_memory_limit: null
openshift_prometheus_oauth_proxy_cpu_requests: null
openshift_prometheus_oauth_proxy_memory_requests: null
